// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVGwaCVyKDftQDeHujaoffNwmLkiWpT9Q',
    appId: '1:695838557254:web:96f0ca670284350d80b647',
    messagingSenderId: '695838557254',
    projectId: 'flutterfirebase-d453d',
    authDomain: 'flutterfirebase-d453d.firebaseapp.com',
    storageBucket: 'flutterfirebase-d453d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsuTnitoOM8IGw66-XzxG4gJ4NQGBL3FA',
    appId: '1:695838557254:android:f9eda4fbc274f0f080b647',
    messagingSenderId: '695838557254',
    projectId: 'flutterfirebase-d453d',
    storageBucket: 'flutterfirebase-d453d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7GDvXGHmQjC0cMCWJG-_5nsjFvaYG30',
    appId: '1:695838557254:ios:72e88cd6f15c0cfb80b647',
    messagingSenderId: '695838557254',
    projectId: 'flutterfirebase-d453d',
    storageBucket: 'flutterfirebase-d453d.appspot.com',
    iosClientId: '695838557254-hrutnfrc3l7dvs1ess8kd98vfghfmolg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7GDvXGHmQjC0cMCWJG-_5nsjFvaYG30',
    appId: '1:695838557254:ios:72e88cd6f15c0cfb80b647',
    messagingSenderId: '695838557254',
    projectId: 'flutterfirebase-d453d',
    storageBucket: 'flutterfirebase-d453d.appspot.com',
    iosClientId: '695838557254-hrutnfrc3l7dvs1ess8kd98vfghfmolg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
